#----------------------------------
# Header
#

menu:
  Home: /
  Archive: /archives

rss: /atom.xml

#----------------------------------
# Footer
#

social:
  GitHub: http://github.com/cheng-kang
  Weibo: http://www.weibo.com/progrant
  Twitter: https://twitter.com/ScotlAnt
  LinkedIn: 

#----------------------------------
# Search
#

search_title: I-330
search_subtitle: 目录
search_placeholder: 不用输入

#----------------------------------
# Comment
#

# fill in with your duoshuo/disqus short_name
duoshuo: 
disqus: 

#----------------------------------
# Analytics
#

# ga for google analytics
# ba for baidu analytics (百度统计)

ga: 
ba: 

#----------------------------------
# Miscellaneous
#

# author_page is your personal website url
author_page: 

home_title: CATALOGUE
archive_title: Archive
article_breadcrumb: I-330
page_breadcrumb: PAGE

favicon: /favicon.png

#----------------------------------
